type Data = {
  [key: string]: { title: string; score: number }[];
};

const data: Data = {
  "2006": [
    { title: "死亡笔记", score: 8.4 },
    { title: "银魂", score: 8.7 },
    { title: "Code Geass 反叛的鲁路修", score: 8.3 },
    { title: "彩云国物语", score: 6.8 },
    { title: "Fate/stay night", score: 7.1 },
    { title: "凉宫春日的忧郁", score: 8.2 },
    { title: "奇幻贵公子", score: 7.1 },
    { title: "少年阴阳师", score: 6.8 },
    { title: "×××HOLiC", score: 7.8 },
    { title: "家庭教师HITMAN REBORN!", score: 7.5 },
    { title: "樱兰高校男公关部", score: 7.6 },
    { title: "翼·年代记 第二部", score: 7.0 },
  ],
  "2007": [
    { title: "幸运星", score: 8.3 },
    { title: "永生之酒", score: 8.2 },
    { title: "大剑", score: 7.4 },
    { title: "旋风管家", score: 7.4 },
    { title: "火影忍者疾风传", score: 7.6 },
    { title: "灼眼的夏娜II", score: 7.0 },
    { title: "萝莉的时间", score: 6.8 },
    { title: "日在校园", score: 6.9 },
    { title: "七色星露", score: 6.0 },
    { title: "再见绝望先生", score: 7.8 },
    { title: "日在校园", score: 6.3 },
    { title: "秒速5厘米", score: 7.9 },
    { title: "四圣兽 ~光阴叙事诗天使谭~ ", score: 5.3 },
  ],
  "2008": [
    { title: "Code Geass 反叛的鲁路修R2", score: 8.3 },
    { title: "×××HOLiC◆继", score: 7.9 },
    { title: "魔法禁书目录", score: 6.8 },
    { title: "狼与香辛料", score: 7.8 },
    { title: "夏目友人帐", score: 8 },
    { title: "今天开始做魔王 第三季", score: 6.6 },
    { title: "纯情罗曼史", score: 7.2 },
    { title: "黑执事", score: 7.0 },
    { title: "隐之王", score: 6.6 },
    { title: "黑执事", score: 7 },
    { title: "秀逗魔导士REVOLUTION", score: 6.8 },
    { title: "圣斗士星矢 极乐净土篇", score: 6.7 },
    { title: "红 Kurenai", score: 6.6 },
  ],
  "2009": [
    { title: "幻灵镇魂曲", score: 7.3 },
    { title: "钢之炼金术师 FULLMETAL ALCHEMIST", score: 8.8 },
    { title: "化物语", score: 8.4 },
    { title: "凉宫春日的忧郁 2009", score: 8 },
    { title: "某科学的超电磁炮", score: 7.5 },
    { title: "犬夜叉 完结篇", score: 7.6 },
    { title: "玛利亚狂热", score: 7.3 },
    { title: "小鸠。", score: 7.0 },
    { title: "战国BASARA", score: 6.8 },
    { title: "07-GHOST", score: 6.8 },
    { title: "续 夏目友人帐", score: 8.0 },
    { title: "白色相簿", score: 7.3 },
  ],
  "2010": [
    { title: "吊带袜天使", score: 8 },
    { title: "四叠半神话大系", score: 8.6 },
    { title: "只有神知道的世界", score: 7.1 },
    { title: "缘之空", score: 6.6 },
    { title: "滑头鬼之孙", score: 6.8 },
    { title: "学园默示录 HIGHSCHOOL OF THE DEAD", score: 6.7 },
    { title: "无头骑士异闻录", score: 7.9 },
    { title: "吸血鬼同盟", score: 6.3 },
    { title: "我的妹妹哪有这么可爱！", score: 7.1 },
    { title: "女仆咖啡厅", score: 7.8 },
    { title: "无法逃离的背叛", score: 5.7 },
    { title: "会长是女仆大人！", score: 6.9 },
    { title: "魔术快斗", score: 6.6 },
  ],
  "2011": [
    { title: "命运石之门", score: 8.8 },
    { title: "Fate/Zero", score: 8.1 },
    { title: "魔法少女小圆", score: 8.6 },
    { title: "我们仍未知道那天所看见的花的名字。", score: 7.6 },
    { title: "罪恶王冠", score: 6.5 },
    { title: "花开伊吕波", score: 7.5 },
    { title: "GOSICK", score: 7.3 },
    { title: "未来日记", score: 7.2 },
    { title: "神的记事本", score: 6.7 },
    { title: "BLOOD-C", score: 6 },
    { title: "未来都市NO.6", score: 7.1 },
    { title: "少年同盟", score: 7.8 },
    { title: "世界第一初恋", score: 7.5 },
  ],
  "2012": [
    { title: "JOJO的奇妙冒险", score: 7.8 },
    { title: "男子高中生的日常", score: 7.9 },
    { title: "伪物语", score: 7.8 },
    { title: "Another", score: 7 },
    { title: "K", score: 6.5 },
    { title: "心理测量者", score: 7.9 },
    { title: "战姬绝唱SYMPHOGEAR", score: 6.5 },
    { title: "刀剑神域", score: 7.3 },
    { title: "邻座的怪同学", score: 7.2 },
    { title: "军火女王", score: 7.2 },
    { title: "妖狐×仆SS", score: 6.7 },
    { title: "黑岩射手", score: 6.4 },
  ],
  "2013": [
    { title: "进击的巨人", score: 8.2 },
    { title: "有顶天家族", score: 7.8 },
    { title: "悠哉日常大王", score: 8 },
    { title: "小魔女学园", score: 7.6 },
    { title: "京骚戏画", score: 7.3 },
    { title: "我的妹妹哪有这么可爱。", score: 6.9 },
    { title: "白色相簿2", score: 7.3 },
    { title: "境界的彼方", score: 6.8 },
    { title: "打工吧！魔王大人", score: 7.1 },
    { title: "Fate/kaleid liner 魔法少女☆伊莉雅", score: 6.9 },
    { title: "翠星之加尔刚蒂亚", score: 7.1 },
    { title: "Q弟侦探因幡", score: 7.1 },
  ],
  "2014": [
    { title: "四月是你的谎言", score: 8 },
    { title: "Fate/stay night [Unlimited Blade Works]", score: 7.5 },
    { title: "游戏人生", score: 7.7 },
    { title: "排球少年", score: 8.1 },
    { title: "甘城光辉游乐园", score: 7 },
    { title: "寄生兽", score: 8 },
    { title: "月刊少女野崎君", score: 7.8 },
    { title: "七大罪", score: 7.2 },
    { title: "斩·赤红之瞳！", score: 6.6 },
    { title: "东京喰种", score: 6.7 },
    { title: "ALDNOAH.ZERO", score: 6.8 },
    { title: "野良神", score: 7.1 },
  ],
  "2015": [
    { title: "OVERLORD", score: 6.9 },
    { title: "暗杀教室", score: 7.3 },
    { title: "死亡遊行", score: 7.1 },
    { title: "夏洛特", score: 6.3 },
    { title: "亚尔斯兰战记", score: 6.9 },
    { title: "监狱学园", score: 7.3 },
    { title: "可塑性记忆", score: 7 },
    { title: "纯情罗曼史3", score: 6.3 },
    { title: "干物妹！小埋", score: 6.8 },
    { title: "终物语", score: 7.8 },
    { title: "学园孤岛", score: 6.9 },
    { title: "终结的炽天使", score: 5.6 },
  ],
  "2016": [
    { title: "为美好的世界献上祝福！", score: 7.6 },
    { title: "JOJO的奇妙冒险 不灭钻石", score: 7.8 },
    { title: "编舟记", score: 7.8 },
    { title: "文豪野犬", score: 6.6 },
    { title: "终末的伊泽塔", score: 6.7 },
    { title: "超级恋人", score: 6.4 },
    { title: "弹丸论破3 -The End of 希望之峰学园- 绝望篇/未来篇", score: 5.5 },
    { title: "暗杀教室 第二季", score: 7.7 },
    { title: "伤物语", score: 8.0 },
    { title: "在下坂本，有何贵干？", score: 6.5 },
    { title: "甲铁城的卡巴内利", score: 5.9 },
    { title: "剑风传奇", score: 6.8 },
  ],
  "2017": [
    { title: "少女终末旅行", score: 8.1 },
    { title: "来自深渊", score: 8.2 },
    { title: "小林家的龙女仆", score: 7.4 },
    { title: "狂赌之渊", score: 7 },
    { title: "末日时在做什么？有没有空？可以来拯救吗？", score: 7.6 },
    { title: "月色真美", score: 7.9 },
    { title: "重启咲良田", score: 7.9 },
    { title: "BanG Dream!", score: 6.4 },
    { title: "幼女战记", score: 7.2 },
    { title: "小魔女学园", score: 7.7 },
    { title: "Just Because!", score: 7.3 },
    { title: "埃罗芒阿老师", score: 6.6 },
    { title: "人渣的本愿", score: 6.6 },
    { title: "珈百璃的堕落", score: 7.1 },
    { title: "笨女孩", score: 6.6 },
    { title: "黑色五叶草", score: 6.5 },
    { title: "如果有妹妹就好了。", score: 6.6 },
    { title: "徒然喜欢你", score: 7.1 },
    { title: "不正经的魔术讲师与禁忌教典", score: 6.2 },
  ],
  "2018": [
    { title: "摇曳露营△", score: 8.2 },
    { title: "碧蓝之海", score: 7.8 },
    { title: "赛马娘 Pretty Derby", score: 7 },
    { title: "紫罗兰永恒花园", score: 7.5 },
    { title: "强风吹拂", score: 8.3 },
    { title: "少女☆歌剧 Revue Starlight", score: 7.9 },
    { title: "擅长捉弄的高木同学", score: 7.5 },
    { title: "佐贺偶像是传奇", score: 7.8 },
    { title: "比宇宙更远的地方", score: 8.2 },
    { title: "青春笨蛋少年不做兔女郎学姐的梦", score: 7.4 },
    { title: "哥布林杀手", score: 6.7 },
    { title: "终将成为你", score: 7.8 },
    { title: "DARLING in the FRANXX", score: 6.2 },
    { title: "来玩游戏吧", score: 7.6 },
    { title: "邪神与厨二病少女", score: 7 },
    { title: "恋如雨止", score: 7.5 },
    { title: "关于我转生变成史莱姆这档事", score: 6.6 },
    { title: "黄金神威", score: 7.5 },
  ],
  "2019": [
    { title: "冰海战记", score: 8.3 },
    { title: "辉夜大小姐想让我告白～天才们的恋爱头脑战～", score: 7.8 },
    { title: "街角魔族", score: 7.5 },
    { title: "鬼灭之刃", score: 7.3 },
    { title: "炎炎消防队", score: 6.5 },
    { title: "女高中生的无所事事", score: 7.6 },
    { title: "慎重勇者 ～这个勇者明明超强却过分慎重～", score: 6.9 },
    { title: "天使降临到了我身边！", score: 7.3 },
    { title: "不吉波普不笑", score: 7.3 },
    { title: "笨拙之极的上野", score: 6.5 },
    { title: "五等分的新娘", score: 6 },
    { title: "约定的梦幻岛", score: 7.6 },
    { title: "只要可爱即使是变态你也会喜欢我吧？", score: 6.1 },
    { title: "Fate/Grand Order -绝对魔兽战线巴比伦尼亚-", score: 6.8 },
    { title: "家有女友", score: 6.3 },
    { title: "君主·埃尔梅罗二世事件簿 魔眼收集列车 Grace note", score: 6.7 },
    { title: "石纪元", score: 7.2 },
  ],
  "2020": [
    { title: "异种族风俗娘评鉴指南", score: 7.7 },
    { title: "魔女之旅", score: 7.1 },
    { title: "安达与岛村", score: 7.3 },
    { title: "异度侵入", score: 7.5 },
    { title: "别对映像研出手！", score: 8.1 },
    { title: "咒术回战", score: 7.1 },
    { title: "总之就是非常可爱", score: 6.3 },
    { title: "隐瞒之事", score: 7.7 },
    { title: "虚构推理", score: 6.3 },
    { title: "恋爱小行星", score: 6.9 },
    { title: "你与我最后的战场，亦或是世界起始的圣战", score: 5.5 },
    { title: "邪神与厨二病少女’", score: 7.3 },
    { title: "转生成为了只有乙女游戏破灭Flag的邪恶大小姐", score: 6.5 },
    { title: "在魔王城说晚安", score: 7 },
    { title: "租借女友", score: 5.8 },
  ],
  "2021": [
    { title: "86 -不存在的战区-", score: 7.6 },
    { title: "无职转生～", score: 7.9 },
    { title: "回复术士的重来人生", score: 6.2 },
    { title: "奇巧计程车", score: 8.5 },
    { title: "打了300年的史莱姆，不知不觉就练到了满级", score: 6.3 },
    { title: "漂流少年", score: 7.8 },
    { title: "堀与宫村", score: 6.8 },
    { title: "派遣战斗员！", score: 6.3 },
    { title: "古见同学有交流障碍症", score: 7 },
    { title: "奇蛋物语", score: 6.8 },
    { title: "我们的重制人生", score: 6.4 },
    { title: "看得见的女孩", score: 6.8 },
    { title: "异世界迷宫黑心企业", score: 6.7 },
    { title: "女神宿舍的宿管君。", score: 5.8 },
  ],
  "2022": [
    { title: "孤独摇滚！", score: 8.4 },
    { title: "莉可丽丝", score: 6.3 },
    { title: "想要成为影之实力者！", score: 7.1 },
    { title: "夏日重现", score: 7.5 },
    { title: "异世界舅舅", score: 7.6 },
    { title: "更衣人偶坠入爱河", score: 7.2 },
    { title: "彻夜之歌", score: 7.4 },
    { title: "测不准的阿波连同学", score: 6.4 },
    { title: "间谍过家家", score: 7.2 },
    { title: "不道德公会", score: 7.1 },
    { title: "链锯人", score: 6.9 },
    { title: "明日同学的水手服", score: 7.5 },
    { title: "契约之吻", score: 6.9 },
    { title: "相合之物", score: 7.8 },
  ],
  "2023": [
    { title: "葬送的芙莉莲", score: 8.5 },
    { title: "药屋少女的呢喃", score: 7.5 },
    { title: "BanG Dream! It's MyGO!!!!!", score: 8.1 },
    { title: "我心里危险的东西", score: 7.8 },
    { title: "超超超超超喜欢你的100个女朋友", score: 7.3 },
    { title: "别当欧尼酱了！", score: 7.6 },
    { title: "跃动青春", score: 7.7 },
    { title: "宝可梦 地平线", score: 7.5 },
    { title: "香格里拉·弗陇提亚～屎作猎人向神作发起挑战～", score: 6.4 },
    { title: "无神世界的神明活动", score: 6.8 },
    { title: "我推的孩子", score: 7.4 },
    { title: "天国大魔境", score: 7.8 },
    { title: "异世界悠闲农家", score: 6.4 },
  ],
  "2024": [
    { title: "败犬女主太多了！", score: 8 },
    { title: "GIRLS BAND CRY", score: 7.6 },
    { title: "胆大党", score: 7.5 },
    { title: "义妹生活", score: 7.3 },
    { title: "迷宫饭", score: 7.8 },
    { title: "我独自升级", score: 6.5 },
    { title: "小市民系列", score: 6.1 },
    { title: "梦想成为魔法少女", score: 7 },
    { title: "青之箱", score: 6.8 },
    { title: "2.5次元的诱惑", score: 6.7 },
    { title: "地。 ―关于地球的运动―", score: 6.2 },
    { title: "失忆投捕", score: 7.9 },
    { title: "不时轻声地以俄语遮羞的邻座艾莉同学", score: 5.6 },
    { title: "悲喜渔生", score: 7.3 },
    { title: "亚托莉 -我挚爱的时光-", score: 6.3 },
    { title: "缘结甘神家", score: 5.9 },
  ],
};

export default data;
